# Copy this file to `.streamlit/secrets.toml` and fill in the values
# to enable Google Sheets backed prompts locally.

[connections.gsheets]
# Full spreadsheet URL (or its ID) that stores the prompt table
spreadsheet = "https://docs.google.com/spreadsheets/d/YOUR-SPREADSHEET-ID/edit#gid=0"

# Optional: name of the worksheet/tab if not using the first one
# worksheet = "Prompts"

# === Service account credentials ===
# Paste all values from your downloaded JSON key without modifications.
type = "service_account"
project_id = "YOUR_PROJECT_ID"
private_key_id = "YOUR_PRIVATE_KEY_ID"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_CONTENT\n-----END PRIVATE KEY-----\n"
client_email = "service-account@your-project.iam.gserviceaccount.com"
client_id = "YOUR_CLIENT_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40your-project.iam.gserviceaccount.com"
